# Generated by Django 6.0 on 2025-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
