# Generated by Django 5.2.9 on 2025-12-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_course_courseplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rest_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
