# Generated by Django 5.2.9 on 2025-12-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_trip_rest_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseplace",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courseplace",
            name="trip",
        ),
        migrations.AddField(
            model_name="trip",
            name="homepage",
            field=models.TextField(blank=True, null=True, verbose_name="홈페이지"),
        ),
        migrations.AddField(
            model_name="trip",
            name="overview",
            field=models.TextField(blank=True, null=True, verbose_name="상세 설명"),
        ),
        migrations.AddField(
            model_name="trip",
            name="parking",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="주차시설"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="tel",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="연락처"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="use_time",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="이용시간"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="rest_date",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="휴무일"
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CoursePlace",
        ),
    ]
