# Generated by Django 5.2.9 on 2026-01-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_remove_courseplace_course_remove_courseplace_trip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="close_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="영업 종료 시간"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="open_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="영업 시작 시간"
            ),
        ),
    ]
