# Generated by Django 5.2.9 on 2026-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_trip_close_time_trip_open_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="is_closed_fri",
            field=models.BooleanField(default=False, verbose_name="금요일 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_mon",
            field=models.BooleanField(default=False, verbose_name="월요일 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_sat",
            field=models.BooleanField(default=False, verbose_name="토요일 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_sun",
            field=models.BooleanField(default=False, verbose_name="일요일 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_thu",
            field=models.BooleanField(default=False, verbose_name="목요일 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_tue",
            field=models.BooleanField(default=False, verbose_name="화요일 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_wed",
            field=models.BooleanField(default=False, verbose_name="수요일 휴무"),
        ),
    ]
