# Generated by Django 5.2.9 on 2026-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_trip_is_closed_fri_trip_is_closed_mon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="is_closed_holiday",
            field=models.BooleanField(
                default=False, verbose_name="명절(설날/추석) 휴무"
            ),
        ),
    ]
