# Generated by Django 5.2.9 on 2026-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_trip_is_closed_holiday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_holiday",
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_chuseok",
            field=models.BooleanField(default=False, verbose_name="추석 연휴 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_new_year",
            field=models.BooleanField(default=False, verbose_name="신정(1월 1일) 휴무"),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_closed_seollal",
            field=models.BooleanField(default=False, verbose_name="설날 연휴 휴무"),
        ),
    ]
