# Generated by Django 5.2.9 on 2026-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0011_remove_trip_is_closed_holiday_trip_is_closed_chuseok_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_chuseok",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_fri",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_mon",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_new_year",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_sat",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_seollal",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_sun",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_thu",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_tue",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_closed_wed",
        ),
        migrations.AddField(
            model_name="trip",
            name="holiday_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="휴무 정보 데이터"
            ),
        ),
    ]
