# Generated by Django 5.2.9 on 2026-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0012_remove_trip_is_closed_chuseok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="average_duration",
            field=models.IntegerField(default=60, verbose_name="평균 체류 시간(분)"),
        ),
    ]
