# Generated by Django 5.2.9 on 2026-01-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0013_trip_average_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="duration_description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="체류 시간 안내문구"
            ),
        ),
    ]
