# Generated by Django 5.2.9 on 2026-01-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0014_trip_duration_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="duration_description",
        ),
    ]
