# Generated by Django 5.2.9 on 2026-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0015_remove_trip_duration_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="holiday_data",
        ),
        migrations.AddField(
            model_name="trip",
            name="operating_info",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="운영 및 휴무 정보 상세"
            ),
        ),
    ]
