# Generated by Django 5.2.9 on 2026-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0016_rename_holiday_data_to_operating_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="detail_meta",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="카테고리별 상세 메타 정보"
            ),
        ),
    ]
