# Generated by Django 5.2.9 on 2025-12-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
